[package]
name = "wasi-shim"
version = "0.1.0"
edition = "2021"
description = "Shims for WASI"
license = "MIT"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
wasi = "=0.11.0"
walrus = "0.23.3"
anyhow = "1.0.95"

[dev-dependencies]
wat = "1.222.0"
